version: '3'
services:
  nginx02:
    image: auth:1.0.0
    container_name: nginx02
    hostname: nginx02
    command: nginx -c /etc/nginx/nginx.conf
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9520:9520"